// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmOKd3MW5fpyki43Kw2ti7pWgihbX7umw',
    appId: '1:1092624965914:android:dcce321c9afee17d720ca3',
    messagingSenderId: '1092624965914',
    projectId: 'graduation-d5fe9',
    storageBucket: 'graduation-d5fe9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCb_zg7N3wjsSTbXrcW9VWoN7ewsXyhwM',
    appId: '1:1092624965914:ios:82b00a6085e642b2720ca3',
    messagingSenderId: '1092624965914',
    projectId: 'graduation-d5fe9',
    storageBucket: 'graduation-d5fe9.appspot.com',
    androidClientId: '1092624965914-t3hrkcfcgdqhpm3vcve6psemoaamqelv.apps.googleusercontent.com',
    iosClientId: '1092624965914-gna374mpj5g1eum86lr3ld7b74jbn0ru.apps.googleusercontent.com',
    iosBundleId: 'com.example.graduationProject',
  );
}
